# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1liXdlwYFjKRt4qj6ObhqxNtyRRFjTkN0
"""

!git clone https://github.com/Tessellate-Imaging/monk_v1

!cd monk_v1/installation/Misc && pip install -r requirements_colab.txt

!wget https://www.dropbox.com/s/wzgyr1dx4sejo5u/dataset.zip
!unzip dataset.zip
!mkdir mod_dataset
!mkdir mod_dataset/images

import cv2
import numpy as np
from glob import glob
from tqdm import tqdm

def convert23channel(imagePath):
  #gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  img = cv2.imread(imagePath)
  img2 = np.zeros_like(img)
  b,g,r = cv2.split(img)
  img2[:,:,0] = b
  img2[:,:,1] = g
  img2[:,:,2] = r
  return img2

imageList = glob("./dataset/images/*.jpg")
for i in tqdm(imageList):
  inPath = i
  out = convert23channel(inPath)
  outPath = "./mod_dataset/images/{}".format(inPath.split('/')[-1])
  cv2.imwrite(outPath,out)

import pandas as pd
gt = pd.read_csv("./dataset/styles.csv",error_bad_lines=False)
gt.head()

label_gt = gt[['id','subCategory']]
label_gt['id'] = label_gt['id'].astype(str) + '.jpg'

label_gt.to_csv('./mod_dataset/subCategory.csv',index=False)





from keras_prototype import prototype

import os
import sys
sys.path.append("./monk_v1/monk/");
import psutil



ktf = prototype(verbose=1);
ktf.Prototype("fashion", "exp7");
ktf.Default(dataset_path="./mod_dataset/images", path_to_csv="./mod_dataset/subCategory.csv", model_name="densenet121", freeze_base_network=True, num_epochs=5);

ktf.Train()

ktf = prototype(verbose=1);
ktf.Prototype("fashion", "exp1");
ktf.Default(dataset_path="./mod_dataset/images", path_to_csv="./mod_dataset/subCategory.csv", model_name="densenet169", freeze_base_network=True, num_epochs=5);
ktf.Train()

from compare_prototype import compare

ctf = compare(verbose=1);
ctf.Comparison("Fashion_Keras_Densenet");

ctf.Add_Experiment("fashion", "exp7");
ctf.Add_Experiment("fashion", "exp1");

ctf.Generate_Statistics();

from IPython.display import Image
Image('workspace/comparison/Fashion_Densenet_Compare/train_accuracy.png')

Image('workspace/comparison/Fashion_Densenet_Compare/stats_training_time.png')

ktf = prototype(verbose=1);
ktf.Prototype("fashion", "exp7", eval_infer=True);

img_name = "dataset/images/7241.jpg";
predictions = ktf.Infer(img_name=img_name);

#Display 
from IPython.display import Image
Image(filename=img_name)

